In [1]:
#import libraries and load the dataset

import pandas as pd
import matplotlib as plt
import numpy as np

df_joan =pd.read_csv('pima-indians-diabetes.csv')
df_joan.columns = ['preg','plas','pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']


In [2]:
#3.a check the missing value
df_joan.isnull().sum()

preg     0
plas     0
pres     0
skin     0
test     0
mass     0
pedi     0
age      0
class    0
dtype: int64

In [3]:
df_joan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 767 entries, 0 to 766
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   preg    767 non-null    int64  
 1   plas    767 non-null    int64  
 2   pres    767 non-null    int64  
 3   skin    767 non-null    int64  
 4   test    767 non-null    int64  
 5   mass    767 non-null    float64
 6   pedi    767 non-null    float64
 7   age     767 non-null    int64  
 8   class   767 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [4]:
#check the statistics of the numeric fields
df_joan.describe()

preg        plas        pres        skin        test        mass  \
count  767.000000  767.000000  767.000000  767.000000  767.000000  767.000000   
mean     3.842243  120.859192   69.101695   20.517601   79.903520   31.990482   
std      3.370877   31.978468   19.368155   15.954059  115.283105    7.889091   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      1.000000   99.000000   62.000000    0.000000    0.000000   27.300000   
50%      3.000000  117.000000   72.000000   23.000000   32.000000   32.000000   
75%      6.000000  140.000000   80.000000   32.000000  127.500000   36.600000   
max     17.000000  199.000000  122.000000   99.000000  846.000000   67.100000   

             pedi         age       class  
count  767.000000  767.000000  767.000000  
mean     0.471674   33.219035    0.348110  
std      0.331497   11.752296    0.476682  
min      0.078000   21.000000    0.000000  
25%      0.243500   24.000000    0.000000  
50%      0.371000   29.000000    0.000000  
75%      0.625000   41.000000    1.000000  
max      2.420000   81.000000    1.000000

In [5]:
df_joan['class'].value_counts()

class
0    500
1    267
Name: count, dtype: int64

In [6]:
# 4. Prepare a standard scaler transformer to transform all the numeric values

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

#prepare transformers and/or pipeline
transformer_joan = StandardScaler()

#separate the target from the features
features = df_joan.drop(columns='class', axis =1)
target = df_joan['class']

#split the train and test
X_train_joan, X_test_joan, y_train_joan, y_test_joan = train_test_split(features,target,test_size=0.3, random_state=42)

#fit the train dataset to the transformer
X_trans_train_joan= transformer_joan.fit_transform(X_train_joan)
X_trans_test_joan = transformer_joan.fit_transform(X_test_joan)


In [7]:
#Define 5 classifiers

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import VotingClassifier, RandomForestClassifier, ExtraTreesClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

logreg_J = LogisticRegression(max_iter = 1400)
rf_J = RandomForestClassifier()
svm_J = SVC()
dtree_J = DecisionTreeClassifier(criterion = "entropy", max_depth = 42)
etrees_J = ExtraTreesClassifier()


voting_clf_J = VotingClassifier(estimators=[('LR', logreg_J), ('RF', rf_J), ('SVM', svm_J), ('DT', dtree_J), ('ET', etrees_J)], voting='hard')


In [8]:
#fit, predict & print predictions

voting_clf_J.fit(X_trans_train_joan,y_train_joan)
predictions = voting_clf_J.predict(X_trans_test_joan[:3])

print("Prediction", predictions)
print("Actual", y_test_joan[:3].values)


Prediction [0 0 0]
Actual [0 0 0]


In [9]:
classifier = [logreg_J, rf_J, svm_J,dtree_J,etrees_J]

for clf in classifier:
    clf.fit(X_trans_train_joan, y_train_joan)
    predictions = clf.predict(X_trans_test_joan[:3])
    print(clf)
    print("Prediction", predictions)
    print("Actual", y_test_joan[:3].values)
    print("\n")

LogisticRegression(max_iter=1400)
Prediction [0 0 0]
Actual [0 0 0]


RandomForestClassifier()
Prediction [0 0 0]
Actual [0 0 0]


SVC()
Prediction [0 0 0]
Actual [0 0 0]


DecisionTreeClassifier(criterion='entropy', max_depth=42)
Prediction [1 1 0]
Actual [0 0 0]


ExtraTreesClassifier()
Prediction [0 0 0]
Actual [0 0 0]




In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier, VotingClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

# a. Logistic Regression (supports probabilities by default)
logreg_J = LogisticRegression(max_iter=1400)

# b. Random Forest Classifier (supports probabilities by default)
rf_J = RandomForestClassifier()

# c. Support Vector Machines (need to set probability=True)
svm_J = SVC(probability=True)

# d. Decision Tree Classifier (supports probabilities by default)
dtree_J = DecisionTreeClassifier(criterion="entropy", max_depth=42)

# e. Extra Trees Classifier (supports probabilities by default)
etrees_J = ExtraTreesClassifier()

# Define a voting classifier for soft voting
voting_clf_soft_J = VotingClassifier(estimators=[('LR', logreg_J), ('RF', rf_J), ('SVM', svm_J), ('DT', dtree_J), ('ET', etrees_J)], voting='soft')


In [11]:
#fit, predict & print predictions

voting_clf_soft_J.fit(X_trans_train_joan,y_train_joan)
predictions = voting_clf_soft_J.predict(X_trans_test_joan[:3])

print("Prediction", predictions)
print("Actual", y_test_joan[:3].values)

Prediction [0 0 0]
Actual [0 0 0]


<h3> Exercise 3 <h3>

In [12]:
#create a pipeline
from sklearn.pipeline import Pipeline
pipeline1_joan = Pipeline([
    ('preprocessor',transformer_joan ),
    ('classifier', etrees_J )
])

pipeline2_joan = Pipeline([
    ('preprocessor',transformer_joan ),
    ('classifier', dtree_J)
])

In [13]:
#fiting the pipeline
pipeline1_joan.fit(X_train_joan,y_train_joan)
pipeline2_joan.fit(X_train_joan,y_train_joan)

Pipeline(steps=[('preprocessor', StandardScaler()),
                ('classifier',
                 DecisionTreeClassifier(criterion='entropy', max_depth=42))])

In [14]:
#evaluate the accuracy score in training data
from sklearn.model_selection import cross_val_score,KFold

kf = KFold(n_splits =10, shuffle = True, random_state =42)
scores_pipeline1 = cross_val_score(pipeline1_joan, X_train_joan, y_train_joan, cv=kf)
scores_pipeline2 = cross_val_score(pipeline2_joan, X_train_joan, y_train_joan, cv=kf)

print("Mean CV Score - Pipeline 1 (Extra Trees):", scores_pipeline1.mean())
print("Mean CV Score - Pipeline 2 (Decision Tree):", scores_pipeline2.mean())

Mean CV Score - Pipeline 1 (Extra Trees): 0.7589098532494758
Mean CV Score - Pipeline 2 (Decision Tree): 0.669601677148847


In [15]:
# getting the perfromance matrix o
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

y_pred_grid_joan = pipeline1_joan.predict(X_test_joan)
accuracy = accuracy_score(y_test_joan,y_pred_grid_joan)
precision = precision_score(y_test_joan, y_pred_grid_joan)
recall = recall_score(y_test_joan, y_pred_grid_joan)
conf_matrix = confusion_matrix(y_test_joan, y_pred_grid_joan)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("Confusion Matrix:\n", conf_matrix)



Accuracy: 0.7705627705627706
Precision: 0.684931506849315
Recall: 0.625
Confusion Matrix:
 [[128  23]
 [ 30  50]]


In [16]:
#perfomance matrix of pipeline2
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

y_pred_grid_joan = pipeline2_joan.predict(X_test_joan)
accuracy = accuracy_score(y_test_joan,y_pred_grid_joan)
precision = precision_score(y_test_joan, y_pred_grid_joan)
recall = recall_score(y_test_joan, y_pred_grid_joan)
conf_matrix = confusion_matrix(y_test_joan, y_pred_grid_joan)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("Confusion Matrix:\n", conf_matrix)

Accuracy: 0.696969696969697
Precision: 0.5581395348837209
Recall: 0.6
Confusion Matrix:
 [[113  38]
 [ 32  48]]


<h3> Exercise 4

In [17]:
#Fine tuning
from sklearn.model_selection import RandomizedSearchCV

parameters = {
    'classifier__min_samples_split': range(10, 3000, 20),
    'classifier__max_depth': range(1, 1000, 2),
    
}

grid_search_94= RandomizedSearchCV(estimator=pipeline1_joan,
                                      param_distributions=parameters,
                                      scoring='accuracy',
                                  
                                      )

grid_search_94.fit(X_train_joan,y_train_joan)



print("Best parameters:", grid_search_94.best_params_)

# Step 23: Print score of the model
print("Grid search score:", grid_search_94.best_score_)
# Compare with original score from Step 14 and explain differences

# Step 24: Print best estimator
best_estimator_joan = grid_search_94.best_estimator_
print("Best estimator:", best_estimator_joan)

Best parameters: {'classifier__min_samples_split': 370, 'classifier__max_depth': 207}
Grid search score: 0.6511249567324333
Best estimator: Pipeline(steps=[('preprocessor', StandardScaler()),
                ('classifier',
                 ExtraTreesClassifier(max_depth=207, min_samples_split=370))])


In [18]:
best_estimator_joan.fit(X_train_joan, y_train_joan)
y_pred_grid_joan = best_estimator_joan.predict(X_test_joan)

accuracy = accuracy_score(y_test_joan, y_pred_grid_joan)
precision = precision_score(y_test_joan, y_pred_grid_joan)
recall = recall_score(y_test_joan, y_pred_grid_joan)
conf_matrix = confusion_matrix(y_test_joan, y_pred_grid_joan)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("Confusion Matrix:\n", conf_matrix)

Accuracy: 0.6666666666666666
Precision: 0.8
Recall: 0.05
Confusion Matrix:
 [[150   1]
 [ 76   4]]


In [19]:
predictions = best_estimator_joan.predict(X_test_joan[:50])

print("Prediction", predictions)
print("Actual", y_test_joan[:50].values)
print("\n")

Prediction [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]
Actual [0 0 0 0 0 0 0 1 0 0 1 1 0 1 1 1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 1 1
 0 0 0 0 1 1 1 0 0 0 1 1 0]




In [20]:
#print accuracy score
train_accuracy = best_estimator_joan.score(X_train_joan, y_train_joan)
test_accuracy = best_estimator_joan.score(X_test_joan, y_test_joan)
print("Training accuracy:", train_accuracy)
print("Testing accuracy:", test_accuracy)

Training accuracy: 0.664179104477612
Testing accuracy: 0.6666666666666666
